lib/pento_web/router.ex
defmodule PentoWeb.Router do
  use PentoWeb, :router

  import PentoWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PentoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PentoWeb do
    pipe_through :browser

    get "/", PageController, :index

  end

  # Other scopes may use custom stacks.
  # scope "/api", PentoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PentoWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", PentoWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", PentoWeb do
    pipe_through [:browser, :require_authenticated_user]
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/products", ProductLive.Index, :index
    live "/products/new", ProductLive.Index, :new
    live "/products/:id/edit", ProductLive.Index, :edit

    live "/products/:id", ProductLive.Show, :show
    live "/products/:id/show/edit", ProductLive.Show, :edit

    live_session :default, on_mount: PentoWeb.Live.UserAuthLive do
      get "/users/settings", UserSettingsController, :edit
      put "/users/settings", UserSettingsController, :update
      live "/guess", WrongLive
    end

  end

  scope "/", PentoWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/pento_web/controllers/user_registration_controller.ex
defmodule PentoWeb.UserRegistrationController do
  use PentoWeb, :controller

  alias Pento.Accounts
  alias Pento.Accounts.User
  alias PentoWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/pento_web/views/user_registration_view.ex
defmodule PentoWeb.UserRegistrationView do
  use PentoWeb, :view
end

lib/pento_web/templates/user_registration/new.html.heex
<h1 class="text-2xl text-cyan-700 font-bold my-4">Register</h1>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="mt-8 max-w-md">
    <div class="grid grid-cols-1 gap-3">
      <label class="block">
        <span class="text-gray-700">Email</span>
        <%= email_input f, :email, required: true, class: "mt-1 block w-full rounded-md
                                                          bg-gray-100 border-transparent
                                                          focus:border-gray-500 focus:bg-white
                                                          focus:ring-0",
                            placeholder: "joe@website.com" %>
        <%= error_tag f, :email %>
      </label>

      <label class="block">
        <span class="text-gray-700">Username</span>
        <%= text_input f, :username, required: true, class: "mt-1 block w-full rounded-md
                                                          bg-gray-100 border-transparent
                                                          focus:border-gray-500 focus:bg-white
                                                          focus:ring-0" %>
        <%= error_tag f, :username %>
      </label>
      
      <label class="block">
        <span class="text-gray-700">Password</span>
        <%= password_input f, :password, required: true, class: "mt-1 block w-full rounded-md
                                                          bg-gray-100 border-transparent
                                                          focus:border-gray-500 focus:bg-white
                                                          focus:ring-0" %>
        <%= error_tag f, :password %>
      </label>

      <%= submit "Register", type: "submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link "Log in", to: Routes.user_session_path(@conn, :new), type: "button", class: "text-center bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), type: "button", class: "text-center bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"%>

    </div>
  </div>
</.form>